services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: "cd myportfolio && python manage.py collectstatic --noinput && ./build.sh"
    startCommand: "cd myportfolio && gunicorn myportfolio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myportfolio.settings
      - key: SECRET_KEY
        generateValue: true
